"""Normalizar sedes y lecturas

Revision ID: 5d6d7fe71813
Revises: 
Create Date: 2025-05-04 17:34:44.021762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d6d7fe71813'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumo_hora',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_sensor', sa.BigInteger(), nullable=False),
    sa.Column('nombre_sede', sa.String(), nullable=True),
    sa.Column('id_localidad', sa.String(), nullable=False),
    sa.Column('hora_inicio_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumo_total_kwh', sa.Float(), nullable=False),
    sa.Column('numero_lecturas', sa.Integer(), nullable=False),
    sa.Column('consumo_promedio_kwh', sa.Float(), nullable=True),
    sa.Column('fecha_procesamiento_utc', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumo_hora_hora_inicio_utc'), 'consumo_hora', ['hora_inicio_utc'], unique=False)
    op.create_index(op.f('ix_consumo_hora_id'), 'consumo_hora', ['id'], unique=False)
    op.create_index(op.f('ix_consumo_hora_id_localidad'), 'consumo_hora', ['id_localidad'], unique=False)
    op.create_index(op.f('ix_consumo_hora_id_sensor'), 'consumo_hora', ['id_sensor'], unique=False)
    op.create_table('sedes',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='ID único de la sede (original del CSV)'),
    sa.Column('nombre_sede', sa.String(), nullable=False, comment='Nombre fusionado o descriptivo'),
    sa.Column('id_localidad', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('fecha_creacion_utc', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion_utc', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sedes_id'), 'sedes', ['id'], unique=False)
    op.create_index(op.f('ix_sedes_id_localidad'), 'sedes', ['id_localidad'], unique=False)
    op.create_table('lecturas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_sede_fk', sa.BigInteger(), nullable=False),
    sa.Column('timestamp_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumo_kwh', sa.Float(), nullable=False),
    sa.Column('fecha_recepcion_utc', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('procesado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_sede_fk'], ['sedes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lecturas_id'), 'lecturas', ['id'], unique=False)
    op.create_index(op.f('ix_lecturas_id_sede_fk'), 'lecturas', ['id_sede_fk'], unique=False)
    op.create_index(op.f('ix_lecturas_procesado'), 'lecturas', ['procesado'], unique=False)
    op.create_index(op.f('ix_lecturas_timestamp_utc'), 'lecturas', ['timestamp_utc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lecturas_timestamp_utc'), table_name='lecturas')
    op.drop_index(op.f('ix_lecturas_procesado'), table_name='lecturas')
    op.drop_index(op.f('ix_lecturas_id_sede_fk'), table_name='lecturas')
    op.drop_index(op.f('ix_lecturas_id'), table_name='lecturas')
    op.drop_table('lecturas')
    op.drop_index(op.f('ix_sedes_id_localidad'), table_name='sedes')
    op.drop_index(op.f('ix_sedes_id'), table_name='sedes')
    op.drop_table('sedes')
    op.drop_index(op.f('ix_consumo_hora_id_sensor'), table_name='consumo_hora')
    op.drop_index(op.f('ix_consumo_hora_id_localidad'), table_name='consumo_hora')
    op.drop_index(op.f('ix_consumo_hora_id'), table_name='consumo_hora')
    op.drop_index(op.f('ix_consumo_hora_hora_inicio_utc'), table_name='consumo_hora')
    op.drop_table('consumo_hora')
    # ### end Alembic commands ###
