"""Crear tabla consumo_dia

Revision ID: 9df5e23cfdc5
Revises: f712c052a73a
Create Date: 2025-05-06 08:52:42.217322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9df5e23cfdc5'
down_revision: Union[str, None] = 'f712c052a73a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumo_dia',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_sede_fk', sa.BigInteger(), nullable=False),
    sa.Column('fecha_utc', sa.Date(), nullable=False),
    sa.Column('consumo_total_diario_kwh', sa.Float(), nullable=False),
    sa.Column('numero_horas_registradas', sa.Integer(), nullable=False),
    sa.Column('consumo_promedio_horario_kwh', sa.Float(), nullable=True),
    sa.Column('fecha_procesamiento_utc', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_sede_fk'], ['sedes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumo_dia_fecha_utc'), 'consumo_dia', ['fecha_utc'], unique=False)
    op.create_index(op.f('ix_consumo_dia_id'), 'consumo_dia', ['id'], unique=False)
    op.create_index(op.f('ix_consumo_dia_id_sede_fk'), 'consumo_dia', ['id_sede_fk'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consumo_dia_id_sede_fk'), table_name='consumo_dia')
    op.drop_index(op.f('ix_consumo_dia_id'), table_name='consumo_dia')
    op.drop_index(op.f('ix_consumo_dia_fecha_utc'), table_name='consumo_dia')
    op.drop_table('consumo_dia')
    # ### end Alembic commands ###
