"""Crear tabla consumo_hora con FK a sedes

Revision ID: f712c052a73a
Revises: 5d6d7fe71813
Create Date: 2025-05-04 17:46:12.177023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f712c052a73a'
down_revision: Union[str, None] = '5d6d7fe71813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumo_hora', sa.Column('id_sede_fk', sa.BigInteger(), nullable=False))
    op.drop_index('ix_consumo_hora_id_localidad', table_name='consumo_hora')
    op.drop_index('ix_consumo_hora_id_sensor', table_name='consumo_hora')
    op.create_index(op.f('ix_consumo_hora_id_sede_fk'), 'consumo_hora', ['id_sede_fk'], unique=False)
    op.create_foreign_key(None, 'consumo_hora', 'sedes', ['id_sede_fk'], ['id'])
    op.drop_column('consumo_hora', 'id_sensor')
    op.drop_column('consumo_hora', 'nombre_sede')
    op.drop_column('consumo_hora', 'id_localidad')
    op.alter_column('sedes', 'id',
               existing_type=sa.BIGINT(),
               comment='ID único de la sede',
               existing_comment='ID único de la sede (original del CSV)',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('sedes_id_seq'::regclass)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sedes', 'id',
               existing_type=sa.BIGINT(),
               comment='ID único de la sede (original del CSV)',
               existing_comment='ID único de la sede',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('sedes_id_seq'::regclass)"))
    op.add_column('consumo_hora', sa.Column('id_localidad', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('consumo_hora', sa.Column('nombre_sede', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('consumo_hora', sa.Column('id_sensor', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'consumo_hora', type_='foreignkey')
    op.drop_index(op.f('ix_consumo_hora_id_sede_fk'), table_name='consumo_hora')
    op.create_index('ix_consumo_hora_id_sensor', 'consumo_hora', ['id_sensor'], unique=False)
    op.create_index('ix_consumo_hora_id_localidad', 'consumo_hora', ['id_localidad'], unique=False)
    op.drop_column('consumo_hora', 'id_sede_fk')
    # ### end Alembic commands ###
